### ISSUE TITLE
Tip: met een Intersection Observer kan je animaties triggeren als de betreffende elementen in beeld komen

### ISSUE THREAD

**Issue by joostf** [r20222/The-Verve-Agency-Careers#13]
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

Voorbeeldje:
https://codepen.io/collection/DyakEw

**Comment by r20222** [comment]
Ik heb dit gemaakt, ik snap nog niet helemaal hoe het werkt. Maar ik ga hier in de toekomst nog meer mee oefenen. Ik heb nu bijvoorbeeld dat de animatie wordt afgespeeld zowel als je naar boven & onderen scrollt. Ik zou eigenlijk willen dat het alleen gebeurt als je naar onderen scrollt.
