### ISSUE TITLE
animatie zaklamp nog niet klaar

### ISSUE THREAD

**Issue by zenitba** [r20222/The-Verve-Agency-Careers#21]
ik vindt de zaklamp leuk idee maar het idee van de zaklamp is hij hoort alleen maar bij de zwarte gedeelte te blijven en hij gaat nu overal waar mijn muis naartoe gaat.

**Comment by r20222** [comment]
Ik wil dit heel graag aanpassen, maar ik heb geen idee hoe ik dit moet aanpassen.

**Comment by r20222** [comment]
Yess het is gelukt dit op te lossen 🎊 Het was heel lastig maar door .light:hover een opacity van 0 te geven, en in javascript een addeventlistener van mouseleave te geven is het gelukt 😄
