### ISSUE TITLE
text bij de zaklamp gedeelte stopt halverwege

### ISSUE THREAD

**Issue by zenitba** [r20222/The-Verve-Agency-Careers#22]
de text bij de zaklamp gedeelte stop halverwege dus meer text bij voegen

**Comment by r20222** [comment]
Ik heb nu iets meer text ingevoegd, maar snap niet hoe ik hier `overflow: hidden;` kan maken. Want nu is nog niet overal tekst omdat de tekst er anders onder vandaan komt en dat wil ik niet.

**Comment by r20222** [comment]
Deze heb ik ook gefixt door de text paragraaf een width en height te geven. En vervolgens heb ik het een overflow hidden gegeven, dus nu kon ik veel tekst toe voegen die geen overflow meer geeft :)
