### ISSUE TITLE
De site loopt af en toe vast tijdens het scrollen

### ISSUE THREAD

**Issue by Amber-vdr** [r20222/The-Verve-Agency-Careers#36]
Dit kan ook aan PolyPane liggen, maar het lijkt alsof de animaties te zwaar zijn waardoor het scrollen niet smooth gaat. Tegen het einde van de site, waar je de aliën ziet en dan door scrolt, loopt de site vast.

**Comment by r20222** [comment]
Zelf heb ik dit niet als ik m'n website op andere browsers bekijk, ik denk dat het door polypane komt.
